### ISSUE TITLE
Arduino tear down process

### ISSUE THREAD

**Issue by mhamilt** [annies-1847/Installation-05-22#5]
I haven't seen an issue yet, so just creating this as a placeholder.

I don't believe there is any kind of formal shutdown of the Arduino in Max quite yet.

Would likely need

- [ ] Routing in the [PollForArduino.maxpat](https://github.com/annies-1847/Installation-05-22/blob/main/max/installation/patchers/PollForArduino.maxpat)
  - [ ] that deals with `1` / `0` input
  - [ ] outputs `bang` or `close` message depending on scenario
- [ ] routing in [ArduinoConnection.maxpat](https://github.com/annies-1847/Installation-05-22/blob/main/max/installation/patchers/ArduinoConnection.maxpat) that
  - [ ] starts connection on `bang`
  - [ ] shutdown Arduino on `close`

**Comment by annies-1847** [comment]
Hey Matthew - sorry for being out of touch yesterday, ended up having to sort something for the degree show. Just taking a look at this now and see the new file in my repository, thank you!!! Is there anything left which needs doing on this issue that I can take a whack at? Otherwise I'll test this new patcher when I do my tweaking next week

**Comment by mhamilt** [comment]
I've just finished tidying the messaging when waiting for Arduino. That should be it all behaving a little bit nicer now. Next stage is just testing.

Pull the change on the `main` branch from the Desktop app and give it a whirl.
